instanceOperations:
  - name: describe-instance
    operation: >
      gcloud compute instances describe --env=${{ENV}} ${{NAME}} --zone=${{ZONE}} --project=${{PROJECT}} --${{ENV}} --format=json
    realtime_output: true
  - name: serial-port-output
    operation: >
      gcloud compute instances get-serial-port-output ${{NAME}} --zone=${{ZONE}} 
  - name: connect-serial-port-output
    operation: >
      gcloud compute connect-to-serial-port ${{NAME}} --zone=${{ZONE}} --format=json
    usecommonparams: true
commonParams:
  ENV:
    choices: sandbox,staging,prod,test
    optional: true
  RESOURCE_NAME:
    default: rishabl
  BUG_REASON:
    optional: true
    dependencies:
      ENV: 'prod'
projectOperation: >
  echo '"tenantProjectId": "rishabl-test",'
projectOperationRegex: '"tenantProjectId":\s"(.+)",'
#validateProjectOperation: echo ${{RESOURCE_NAME}}-${{ENV}}
preRDPOperations:
  - name: echo hello
    operation: echo ${{NAME}} ${{RESOURCE_NAME}}
    dependencies:
      ENV: 'test'
operations: 
  - name: echo-vm
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    operation: >
      echo ${{NAME}} ${{RESOURCE_NAME}}
    dependencies:
      ENV: 'test'
    params:
      NAME:
        optional: true
  - name: echo-vm2
    description: Creates a Gcloud VM
    operation: >
      bash -c 'while true; do "echo ${{NAME}}"; sleep 1; done'
    params:
      NAME: 
        type: string
        default: new-instance
    realtime_output: true
  - name: create-vm2
    description: Creates a Gcloud VM
    operation: >
      gcloud beta compute
      instances create ${{NAME}} 
      --zone=us-central1-a 
      --machine-type=${{MACHINE_TYPE}}
      --subnet=default 
      --network-tier=${{NETWORK_TIER}}
      --maintenance-policy=MIGRATE 
      --service-account=1053439593197-compute@developer.gserviceaccount.com 
      --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append 
      --image=${{IMAGE}}
      --image-project=eip-images 
      --boot-disk-size=${{DISK_SIZE}}
      --boot-disk-type=pd-standard 
      --boot-disk-device-name=${{NAME}}
      --reservation-affinity=any
    params:
      NAME: 
        type: string
        default: new-instance
      IMAGE: 
        type: string
      MACHINE_TYPE:
        type: string
      DISK_SIZE: 
        type: number
      NETWORK_TIER:
        type: string
        optional: true
  - name: create-firewall
    description: creates a firewall
    operation: >
      gcloud compute firewall-rules create ${{NAME}}
      --direction=INGRESS
      --action=allow
      --rules=tcp:${{TCP}}
      --source-ranges=35.235.240.0/20
      --network=${{NETWORK}}
    params:
      NAME:
      TCP:
      NETWORK:
# workflows:
#   - name: instance-unhealthy
#     description: workflow for unhealthy instances
#     operations: echo-vm2,create-vm2, bad
