CommonVariables:
  PROJECT:
    type: string
    
commands: 
  - name: create-vm
    command: >
      gcloud beta compute
      --project=$PROJECT
      instances create $NAME 
      --zone=us-central1-a 
      --machine-type=$MACHINE_TYPE 
      --subnet=default 
      --network-tier=$NETWORK_TIER 
      --maintenance-policy=MIGRATE 
      --service-account=1053439593197-compute@developer.gserviceaccount.com 
      --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append 
      --image=$IMAGE
      --image-project=eip-images 
      --boot-disk-size=$DISK_SIZE 
      --boot-disk-type=pd-standard 
      --boot-disk-device-name=$NAME
      --reservation-affinity=any
    variables:
      NAME: 
        type: string
        default: new-instance
      IMAGE: 
        type: string
      MACHINE_TYPE:
        type: string
      DISK_SIZE: 
        type: number
      NETWORK_TIER:
        type: string