name: Run Chrome Extension tests
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths:
      - 'extension/*'

jobs:
  build:
    # Job name is Greeting
    name: Run Jest tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test